//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pjrFormula_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotCar
    {
        public int id_Pilot { get; set; }
        public int id_Car { get; set; }
        public System.DateTime event_date { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Pilot Pilot { get; set; }

        public override string ToString()
        {
            return $" Piloto: {this.Pilot}\n" +
                $" Carro: {this.Car}\n" +
                $"Data do evento: {this.event_date}\n";
        }
    }
}
